zuul:
  routes:
    auth-service:
      url: http://${AUTH_HOST:localhost}:5000
    rates-stub:
      path: /rates/**
      url: ${RATES_URL:http://localhost:18080}
      stripPrefix: true
      sensitiveHeaders:
